baseURL = "https://hadi7546.me"
languageCode = "en-us"
theme = "hello-friend-ng"
title = "Hadi Azarnasab"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
paginate = 10 
rssLimit = 10 

# googleAnalytics = ""
disqusShortname = "hadi7546"

archetypeDir = "archetypes"
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "public"

buildDrafts = false
buildExpired = false
buildFuture = false
canonifyURLs = true

disable404 = false
disableHugoGeneratorInject = false
disableRSS = true
disableSitemap = false
enableEmoji = true
enableGitInfo = false
enableMissingTranslationPlaceholders = false
enableRobotsTXT = true

[author]
name = "Hadi Azarnasab"

[blackfriday]
hrefTargetBlank = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[params]
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
dateformShort = "Jan 2"

# Metadata mostly used in document's head
# 
description = "Hadi Azarnasab Personal Website"
images = ["images/hadi-latest.png"]
keywords = "Hadi, Hadi7546, HadiAzarnasab"

homeSubtitle = "A 16 Y/O Student | Flutter & GoLang Developer | Astronomy & Physics & AI/ML Lover"

disableReadOtherPosts = false
enableGlobalLanguageMenu = false
enableSharingButtons = true
enableThemeToggle = true

customCSS = []
customJS = []

justifyContent = false
[params.commento]
url = ""

[params.footer]
author = true
copyright = false
rss = false
trademark = true

bottomText = []
topText = []

[params.favicon.color]
mask = "#1b1c1d"
msapplication = "#1b1c1d"
theme = "#1b1c1d"

[params.logo]
logoCursorDisabled = true
logoHomeLink = "/"
logoMark = " "
logoText = "Hadi7546"

[params.portrait]
alt = "Portrait"
path = "images/hadi-latest-cropped.png"

[[params.social]]
name = "twitter"
url = "social/twitter"

[[params.social]]
name = "github"
url = "social/github"

[[params.social]]

name = "linkedin"
url = "/social/linkedin"

[[params.social]]
name = "telegram"
url = "social/telegram"

[[params.social]]
name = "discord"
url = "social/discord"

[[params.social]]
name = "spotify"
url = "social/spotify"

[[params.social]]
name = "monkeytype"
url = "social/monkeytype"

[[params.social]]
name = "mastodon"
url = "social/mastodon"

[[params.social]]
name = "email"
url = "mailto:hi@hadi7546.ir"

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "about/"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "https://blog.hadi7546.ir"

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "https://resume.hadi7546.ir"
